Linkup_SocialNetwork/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('homePage.urls')),
    path('account/', include('accounts.urls')),
    path('u/', include('userProfile.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name= 'accounts'

urlpatterns = [
    path('login/', views.Login.as_view(), name= "login"),
    path('signup/', views.Signup.as_view(), name= "signup"),
    path('logout/', views.Logout.as_view(), name= "logout"),
    path('ajax-search/', views.UserSearch.as_view(), name= "userSearch"),
]

posts/urls.py
from posts.models import Post
from django.urls import path
from .views import *

app_name= 'Posts'

urlpatterns = [
    path('', PostView.as_view(), name= "post"),
    path('ajax-ctrls/', PostCtrlsView.as_view(), name= "postCtrls"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator

class UserProfile(models.Model):
    email= models.EmailField()
    f_name= models.CharField(max_length=20)
    l_name= models.CharField(max_length=20)
    fullName=models.CharField(max_length=40, blank=True, null=True)
    user= models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    pfp= models.ImageField(validators=[FileExtensionValidator(['jpg'])], default="placeholder.jpg", upload_to= 'pfp', verbose_name='Profile Picture')
    pgp= models.ImageField(validators=[FileExtensionValidator(['jpg'])], default="placeholder.jpg", upload_to= 'pgp', verbose_name='Background Picture')
    bio = models.TextField(max_length=500, blank=True)
    b_date = models.DateField()
    gender = models.CharField(max_length=1)

    def __str__(self):
        return self.user.username

accounts/forms.py
from django.forms import widgets, ModelForm, ValidationError
from .models import UserProfile
from django.core.files.images import get_image_dimensions


class UserProfileForm(ModelForm):
    class Meta:
        model= UserProfile
        fields= [
            'email',
            'f_name', 'l_name', 
            'bio', 'b_date',
            'pfp', 'pgp','gender'
        ]
        GENDER_CHOICES = {
            ('M', 'Male'),
            ('F', 'Female'),
        }
        exclude={'user', 'fullName'}
        widgets = {
            'email': widgets.EmailInput(),
            'b_date': widgets.SelectDateWidget(),
            'gender': widgets.RadioSelect(choices=GENDER_CHOICES),
            'f_name': widgets.TextInput(),
            'l_name': widgets.TextInput(),
            'bio': widgets.TextInput(),
            'user': widgets.TextInput(),
            'fullName': widgets.TextInput(),
        }
    def clean_pgp(self):
        pgp= self.cleaned_data.get('pgp')
        if not pgp:
            raise ValidationError("no background image !")
        else:
            w,h= get_image_dimensions(pgp)
            if w <  2037 :
                raise ValidationError('the image width is %i , its suppose to be 820'%w)
            if h <  754 :
                raise ValidationError('the image width is %i , its suppose to be 312'%h)
            return pgp

accounts/views.py
from django.shortcuts import redirect, render
from django.http import JsonResponse
from django.contrib.auth.forms import  AuthenticationForm, UserCreationForm
from .forms import UserProfileForm
from django.contrib.auth import login, logout
from django.views import View

from .models import UserProfile

class Login(View):

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('homePage:home')
        return render(request, 'login.html')
    
    def post(self, request):
        loginData= AuthenticationForm(data= request.POST)
        if loginData.is_valid():
            login(request, loginData.get_user())
            return redirect('homePage:home')
        form= AuthenticationForm()
        msg="Wrong login info"
        return render(request, 'login.html', {'form': form, 'msg':msg})

class Signup(View):
    
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('homePage:home')
        return render(request, 'signup.html')

    def post(self, request):
        userForm = UserCreationForm(request.POST)    
        profilForm = UserProfileForm(request.POST, request.FILES)
        if userForm.is_valid():
            myUser=userForm.save(commit=False)
            myForm= profilForm.save(commit=False)
            myForm.fullName= myForm.f_name +" "+ myForm.l_name
            myForm.user= myUser
            if profilForm.is_valid():
                myUser.save()
                myForm.save()
                login(request, myUser)
            return redirect('homePage:home')
        else:
            msg="Wrong login info"
            return render(request, 'signup.html',{'msg':msg})

class Logout(View):
    def get(self, request):
        if request.user.is_authenticated:
            logout(request)
        return redirect('accounts:login')

class UserSearch(View):
    def get(self, request):
        html=[]
        searchKey= request.GET.get('searchKey')
        allProfiles= UserProfile.objects.filter(fullName__icontains=searchKey)
        for p in allProfiles:
            html.append('''
                <div class="row mt-4 m-auto">
                    <img class="smImg col-4" src="'''+p.pfp.url+'''" alt="">
                    <h5 class="col-8" style="place-self: center;">
                    <a class="profileLink" href="/u/'''+p.user.username+'''"> ''' +p.fullName+''' </a>
                    </h5>
                </div>
            ''')
        data={
           'html':html
        }
        return JsonResponse(data)

accounts/templates/login.html
{% extends 'mainTemplate.html' %}
    {% block title %}Login{% endblock %}
    {% block content %}
        <h1></h1>
        <form class="form1" action="" method="post">
            {% csrf_token %}
            <h1 class="mb-5 text-decoration-underline">Login</h1>
            <h3 class="alert-danger mt-5">{{msg}}</h3>
            <br><hr>
            <h3>Please enter valid login information.</h3>
            <p> 
                <label for="id_username"><i class="fa fa-user"></i></label>
                <input  placeholder="Username" type="text" name="username" maxlength="150" required id="id_username">
            </p>
            <p>
                <label for="id_password"><i class="fa fa-key"></i></label> 
                <input  placeholder="Enter your Password" type="password" name="password" required id="id_password">
            </p>
            <button class="btn btnNo2" type="submit">Login</button>
            <p class="mt-3">Dont have an account ? <a href="{% url 'accounts:signup' %}">Create now!</a></p>
        </form>
    {% endblock %}

accounts/templates/signup.html
{% extends 'mainTemplate.html' %}
    {% block title %}Signup{% endblock %}
    {% block content %}
        <form enctype="multipart/form-data" class="signupForm" method="post">
            {% csrf_token %}
            <div class="front container w-100">
                <h1 class="mb-5 text-decoration-underline">User info.</h1>
                <p>
                    <label for="id_username"><i class="fa fa-user"></i></label> 
                    <input placeholder="Username" type="text" name="username" maxlength="150" required id="id_username"> 
                </p>
                <p>
                    <label for="id_email"><i class="fa fa-envelope"></i></label> 
                    <input placeholder="Email:ex@ex.com" type="email" name="email" maxlength="254" required id="id_email">
                </p>
                <p>
                    <label for="id_password1"><i class="fa fa-key"></i></label> 
                    <input  placeholder="Enter your Password" type="password" name="password1"  required id="id_password1"> 
                </p>
                <p>
                    <label for="id_password2"><i class="fa fa-key"></i></label> 
                    <input placeholder="Re-enter the Password" type="password" name="password2"  required id="id_password2"> 
                </p>
                <button class="btn btnNo1" data-action="flip">Next</button>
                <p class="mt-3">
                    Already has an account ? 
                    <a href="{% url 'accounts:login' %}">Login now!</a>
                </p>
            </div>
            <div class="back">
                <h1 class="mb-5 text-decoration-underline">Profile</h1>
                <h3 class="alert-danger mt-5">{{msg}}</h3>
                <br>
                <br><br>
                <p style="block-size: 200px;">
                    <label id="img_pgp" for="id_pgp" 
                    style="
                    width: 90%; 
                    height: 300px;
                    background-color: #222;  
                    background-size:100% 100%;">click to change background-picture</label> 
                    <input type="file" name="pgp" accept="image/*" id="id_pgp" onchange="pgpURL(this);">
                </p>
                <p style="block-size: 200px;">
                    <label id="img_pfp"  for="id_pfp"
                    style="
                    width: 150px; 
                    height: 150px;
                    background-color: #333;  
                    background-size:100% 100%;">Profile-picture</label> 
                    <input type="file" name="pfp" accept="image/*" id="id_pfp" onchange="pfpURL(this);">
                </p>
                <p style="block-size:auto;">
                    <label for="id_f_name"><i class="fa fa-address-card"></i></label> 
                    <input style="width: 40%;" type="text" name="f_name" class="col-5" placeholder="First name" maxlength="20" required id="id_f_name">
                    <input style="width: 40%;" type="text" name="l_name" class="col-5" placeholder="Last name" maxlength="20" required id="id_l_name">
                </p>
                <p style="block-size:auto;">
                    <label for="id_bio"><i class="fa fa-info"></i></label> 
                    <input name="bio" placeholder="your bio..." maxlength="200" id="id_bio"></input>
                </p>
                <p style="block-size:autio; display: inline;">
                    <label for="id_b_date_month" style="background-color: transparent;">Birth Date</label> 
                    <select name="b_date_month" required="" id="id_b_date_month" class="col-12"><option value="1">January</option><option value="2">February</option><option value="3">March</option><option value="4">April</option><option value="5">May</option><option value="6">June</option><option value="7">July</option><option value="8">August</option><option value="9">September</option><option value="10">October</option><option value="11">November</option><option value="12">December</option>
                    </select>
                    <select name="b_date_day" required="" id="id_b_date_day" class="col-12"><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option><option value="6">6</option><option value="7">7</option><option value="8">8</option><option value="9">9</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14">14</option><option value="15">15</option><option value="16">16</option><option value="17">17</option><option value="18">18</option><option value="19">19</option><option value="20">20</option><option value="21">21</option><option value="22">22</option><option value="23">23</option><option value="24">24</option><option value="25">25</option><option value="26">26</option><option value="27">27</option><option value="28">28</option><option value="29">29</option><option value="30">30</option><option value="31">31</option>
                    </select>
                    <select name="b_date_year" required="" id="id_b_date_year" class="col-12"><option value="1960">1960</option><option value="1961">1961</option><option value="1962">1962</option><option value="1963">1963</option><option value="1964">1964</option><option value="1965">1965</option><option value="1966">1966</option><option value="1967">1967</option><option value="1968">1968</option><option value="1969">1969</option><option value="1970">1970</option><option value="1971">1971</option><option value="1972">1972</option><option value="1973">1973</option><option value="1974">1974</option><option value="1975">1975</option><option value="1976">1976</option><option value="1977">1977</option><option value="1978">1978</option><option value="1979">1979</option><option value="1980">1980</option><option value="1981">1981</option><option value="1982">1982</option><option value="1983">1983</option><option value="1984">1984</option><option value="1985">1985</option><option value="1986">1986</option><option value="1987">1987</option><option value="1988">1988</option><option value="1989">1989</option><option value="1990">1990</option><option value="1991">1991</option><option value="1992">1992</option><option value="1993">1993</option><option value="1994">1994</option><option value="1995">1995</option><option value="1996">1996</option><option value="1997">1997</option><option value="1998">1998</option><option value="1999">1999</option><option value="2000">2000</option><option value="2001">2001</option><option value="2002">2002</option><option value="2003">2003</option><option value="2004">2004</option><option value="2005">2005</option><option value="2006">2006</option><option value="2007">2007</option><option value="2008">2008</option><option value="2009">2009</option><option value="2010">2010</option><option value="2011">2011</option><option value="2012">2012</option><option value="2013">2013</option><option value="2014">2014</option><option value="2015">2015</option>
                    </select>
                
                    <ul id="id_gender" style="block-size:auto; margin-left: 6rem;">
                        <li><label for="">Gender</label></li>
                        <li>
                            <label for="id_gender_0">
                                <i class="fa fa-female"></i>
                            </label>
                            <input type="radio" name="gender" value="F" maxlength="1" required="" id="id_gender_0">
                        </li>
                        <li>
                            <label for="id_gender_1">
                                <i class="fa fa-male"></i>
                            </label>
                            <input type="radio" name="gender" value="M" maxlength="1" required="" id="id_gender_1">
                        </li>
                    </ul>
                </p>
                <p class="mt-1">
                    By clicking Create, you agree to our Terms and Cookie Use!
                </p>
                <input type="text" name="user" class="hidden" id="id_user">
                <input type="text" name="fullName" class="hidden" id="id_fullName">
                <button class="btn btnNo1 flip float-start ms-5 mt-1" data-action="flip">Back</button>
                <button class="btn btnNo2 float-end mx-5 mt-1" type="submit">Create</button>
            </div>
        </form>
    {% endblock %}