Linkup_SocialNetwork/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('homePage.urls')),
    path('account/', include('accounts.urls')),
    path('u/', include('userProfile.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from posts.models import Post
from django.urls import path
from .views import *

app_name= 'Posts'

urlpatterns = [
    path('', PostView.as_view(), name= "post"),
    path('ajax-ctrls/', PostCtrlsView.as_view(), name= "postCtrls"),
]

userProfile/urls.py
from django.urls import path
from .views import *

app_name= 'userProfile'

urlpatterns = [
    path('<slug:user>', Profile.as_view(), name= "Profile"),
    path('friends/<slug:user>', FriendsCTRL.as_view(), name= "FriendsCTRL"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator

class UserProfile(models.Model):
    email= models.EmailField()
    f_name= models.CharField(max_length=20)
    l_name= models.CharField(max_length=20)
    fullName=models.CharField(max_length=40, blank=True, null=True)
    user= models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    pfp= models.ImageField(validators=[FileExtensionValidator(['jpg'])], default="placeholder.jpg", upload_to= 'pfp', verbose_name='Profile Picture')
    pgp= models.ImageField(validators=[FileExtensionValidator(['jpg'])], default="placeholder.jpg", upload_to= 'pgp', verbose_name='Background Picture')
    bio = models.TextField(max_length=500, blank=True)
    b_date = models.DateField()
    gender = models.CharField(max_length=1)

    def __str__(self):
        return self.user.username

posts/models.py
from django.db import models
from accounts.models import UserProfile

class Post(models.Model):
    author= models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    content= models.TextField(max_length=10000)
    media= models.FileField(null=True, blank=True, upload_to='posts_media')
    date= models.DateTimeField(auto_now_add=True) 

    def allUserPosts(theUser):
        posts=Post.objects.filter(author= UserProfile.objects.get(user=theUser)).order_by('-date')
        return posts

    def likes(self):
        myPost= Post.objects.get(id= self.id)
        likesObj= Like.objects.filter(post=myPost).values_list('user',flat=True)
        return list(likesObj)

    def comments(self):
        myPost= Post.objects.get(id= self.id)
        commsObj= Comment.objects.filter(post=myPost)
        return commsObj

class Like(models.Model):
    user= models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    post= models.ForeignKey(Post, on_delete=models.CASCADE)



class Comment(models.Model):
    user= models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    post= models.ForeignKey(Post, on_delete=models.CASCADE)
    content= models.TextField(max_length=5000,null=False, blank=False)

userProfile/models.py
from django.db import models
from accounts.models import UserProfile
from django.contrib.auth.models import User

class Friend(models.Model):
    status_choices = {
        ('B', 'Binding'),
        ('F', 'Friends')
    }
    user1= models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    user2= models.ForeignKey(User, on_delete=models.CASCADE, related_name='reciver')
    status= models.CharField(choices=status_choices, max_length=2)
    
    def __str__(self):
        return (self.user1.username + " > " + self.user2.username + " = " + self.status)

    def friendList(user):
        userFriends=[]
        f1= Friend.objects.filter(user1=user.id, status= 'F').values(f_id=models.F('user2'))
        f2= Friend.objects.filter(user2=user.id, status= 'F').values(f_id=models.F('user1'))
        for f in f2:
            userFriends.append(UserProfile.objects.get(user=f['f_id']))
        for f in f1:
            userFriends.append(UserProfile.objects.get(user=f['f_id']))
        return (userFriends)

    def friendRequestsList(user):
        userFriends=[]
        allFriends= Friend.objects.filter(user2=user.id ,status= 'B').values('user1')
        for f in allFriends:
            userFriends.append(UserProfile.objects.get(user=f['user1']))
        return (userFriends)

    def sentFriendRequests(user):
        userFriends=[]
        allFriends= Friend.objects.filter(user1=user.id, status= 'B').values('user2')
        for f in allFriends:
            userFriends.append(UserProfile.objects.get(user=f['user2']))
        return (userFriends)

userProfile/views.py
from django.shortcuts import redirect, render
from django.views import View
from .models import Friend
from django.contrib.auth.models import User
from accounts.models import UserProfile
from posts.models import Post

class Profile(View):

    def getUserProfile(self, user):
        myUser=  UserProfile.objects.get(user= user.id)
        return myUser

    def get(self, request, user):
        myUser= self.request.user
        myUserInfo= self.getUserProfile(myUser)
        myFriends= Friend.friendList(myUser)
        theUser= User.objects.get(username= user)
        theUserProfile= self.getUserProfile(theUser)
        userFriends=  Friend.friendList(theUser)
        userFriendReq=  Friend.friendRequestsList(myUser)
        sentUserFriendReq=  Friend.sentFriendRequests(myUser)
        userPosts= list(Post.allUserPosts(theUser))
        content={
            'userProfile':myUserInfo,
            'profileInfo':theUserProfile,
            'myFriendList':myFriends,
            'userFriendList':userFriends,
            'friendRequests':userFriendReq,
            'sentFriendRequests':sentUserFriendReq,
            'allPosts':userPosts
            }
        return render(request, 'profile.html',content )

    def post(self, request, user):
        myUser= self.request.user
        enteredPass= request.POST.get('userPassword')
        if myUser.check_password(enteredPass):
            myUserInfo= self.getUserProfile(myUser)

            myUserInfo.f_name= request.POST.get('f_name')
            myUserInfo.l_name= request.POST.get('l_name')
            myUserInfo.fullName= myUserInfo.f_name +" "+ myUserInfo.l_name

            myUserInfo.email= request.POST.get('email')
            myUserInfo.gender= request.POST.get('gender')

            myUserInfo.save()
        return redirect ("userProfile:Profile", myUser)
    
class FriendsCTRL(View):

    def post(self, request, user):
        method= request.POST.get("_method")
        if method == "add":          
            myuser1=  User.objects.get(username= self.request.user)
            myuser2=  User.objects.get(username= user)
            if request.POST.get('status') == 'B':
                Newfriends= Friend() 
                Newfriends.user1= myuser1
                Newfriends.user2= myuser2
                Newfriends.status= 'B'
                Newfriends.save()
            if request.POST.get('status') == 'F':
                Newfriends= Friend.objects.filter(user2=myuser1, user1=myuser2).update(status='F')
        elif method == "delete":
            myuser1=  self.request.user
            myuser2=  User.objects.get(username= user)
            friendShip= (Friend.objects.filter(user1=myuser1, user2=myuser2)) | (Friend.objects.filter(user1=myuser2 ,user2=myuser1))
            friendShip.delete()
        if request.POST.get('next'):
            return redirect (request.POST.get('next'))
        return redirect ("userProfile:Profile", user)

userProfile/templates/profile.html
{% extends 'mainTemplate.html' %}
    {% block title %} Profile {% endblock %}
    {% block content %}
    <div class="col-8 m-auto mb-5" style=" background-color: #2e2e2e;">
        <div id="ProfileInfo">
            <img src="{{profileInfo.pgp.url}}" class="border-bottom" width="100%" height="450px">
            <img src="{{profileInfo.pfp.url}}" class="border" style="margin-top: -10rem;" width="150px" height="150px">
            <h1 style="text-transform:capitalize;">
                <span>{{profileInfo.fullName}}</span>
            </h1>
            <h3>{{profileInfo.bio}}</h3>
            <ul class=" nav nav-tabs profileNav">
                <li >
                    <a href="#posts-tab" data-toggle="tab">Posts</a>
                </li>
                <li>
                    <a href="#about-tab" data-toggle="tab">About</a>
                </li>
                <li>                    
                    <a href="#friends-tab" data-toggle="tab">Friends</a>
                </li>
                {% if user.id == profileInfo.user.id %}
                {% elif profileInfo in myFriendList %}
                    <form action="{% url 'userProfile:FriendsCTRL' user=profileInfo.user.username%}" method="post">
                        {% csrf_token %}
                        <input type="text" hidden name="_method" id="id_method" value="delete">
                        <button class="btn btnNo1" type="submit">Unfriend</button>
                    </form>
                {% elif profileInfo in friendRequests %}
                    <form action="{% url 'userProfile:FriendsCTRL' user=profileInfo.user.username%}" method="post">
                        {% csrf_token %}
                        <input type="text" hidden name="_method" id="id_method" value="add">
                        <input type="text" hidden name="status" id="id_status" value="F">
                        <button class="btn btnNo2" type="submit">Accept request</button>
                    </form>
                {% elif profileInfo in sentFriendRequests %}
                    <form action="{% url 'userProfile:FriendsCTRL' user=profileInfo.user.username%}" method="post">
                        {% csrf_token %}
                        <input type="text" hidden name="_method" id="id_method" value="delete">
                        <button class="btn btnNo1" type="submit">Cancel request</button>
                    </form>
                {% else %}
                    <form action="{% url 'userProfile:FriendsCTRL' user=profileInfo.user%}" method="post">
                        {% csrf_token %}
                        <input type="text" hidden name="_method" id="id_method" value="add">
                        <input type="text" hidden name="status" id="id_status" value="B">
                        <button class="btn btnNo2" type="submit">add friend</button>
                    </form>
                {% endif %}
            </ul>
        </div>
    </div>
    <div class="mt-5 col-6 m-auto mb-5">
        <div class="tab-content">
            <div  class="tab-pane active" id="posts-tab">
                {% if user.id == profileInfo.user.id %}
                <form id="newPost" action="{% url 'Posts:post' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <label class="row m-auto">
                        <img class="smImg col-4 border-0" src="{{userProfile.pfp.url}}" alt="">
                        <textarea class="postContent" style="width: 79rem;" maxlength="10000" placeholder="create a post..."  name="content" id="id_content"></textarea>
                    </label>
                    <div class="row mt-5 m-auto">
                        <label class="col-3 postCtrls" for="id_media">Image/Video</label>
                        <input type="file" id="id_media" name="media" class="postFiles">
                        <input type="text" hidden name="_for" value="forPost">
                        <input type="text" hidden name="_method" value="add">
                        <span class="col-7"></span>
                        <button  class="col-2 btnNo2" type="submit">Post</button>
                    </div>
                </form>
                {% endif %}
                {% include 'post.html' %}
            </div>
            <div  class="tab-pane" id="about-tab">
                <div class="profileTabs">
                    <h1 class="d-inline" style="font-size: 5rem;">About:</h1>
                    {% if user.id == profileInfo.user.id %}
                    <button onclick="editUser('profileInfo.user.username')" class="btn btnNo2 float-end" type="submit">Edit Info</button>
                    {% endif %}
                    <hr>
                    <br>
                    <table class="profileInfo ms-5 w-100">
                        <tr>
                            <td><span>Full name : </span>{{profileInfo.fullName}}</td>
                            <td class="ps-5"><span>Username/slug : </span>{{profileInfo.user.username}}</td>
                        </tr>
                        <tr>
                            <td><span>E-mail : </span>{{profileInfo.email}}</td>
                            <td class="ps-5"><span>Gender : </span>{{profileInfo.gender}}</td>
                        </tr>
                        <tr>
                            <td><span>Birthdate : </span>{{profileInfo.b_date}}</td>
                        </tr>
                    </table>
                    
                    <table class="editProfileInfo hidden editForm ms-5 w-100">
                        <form method="post" action="{% url 'userProfile:Profile' user=userProfile.user.username%}">
                            {% csrf_token %}
                            <tr>
                                <td><span>First name : </span>
                                    <input value="{{profileInfo.f_name}}" type="text" name="f_name"  id="id_f_name">
                                </td>
                                <td><span>Last name : </span>
                                    <input type="text" value="{{profileInfo.l_name}}" name="l_name"  id="id_l_name">
                                </td>
                            </tr>
                            <tr>
                                <td><span>E-mail : </span>
                                    <input type="text" name="email" value="{{profileInfo.email}}">
                                </td>
                                <td><span>Gender : </span>
                                    <ul id="id_gender" style="block-size:auto; ">
                                        <li >
                                            <label for="id_gender_0">
                                                <i class="fa fa-female"></i>
                                            </label>
                                            <input type="radio" name="gender" value="F" maxlength="1" required="" id="id_gender_0">
                                        </li>
                                        <li>
                                            <label for="id_gender_1">
                                                <i class="fa fa-male"></i>
                                            </label>
                                            <input type="radio" name="gender" value="M" maxlength="1" required="" id="id_gender_1">
                                        </li>
                                    </ul>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <span for="userPassword">Your Password:</span>
                                    <input name="userPassword" type="password">
                                </td>
                                <td>
                                   <button class="btn btnNo2" type="submit">Edit</button> 
                                </td>
                            </tr>                        
                        </form>
                    </table>
                </div>
            </div>
            <div  class="tab-pane" id="friends-tab">
                <div class="profileTabs">
                    <h1 style="font-size: 5rem;">Friends:</h1>
                    <hr>
                    <br>
                    <table class="ms-5 w-100">
                        {% for f in userFriendList %}
                        <tr>
                            <td>
                                <img class="smImg col-4 border-0" style="width: 6rem; height: 6rem;" src="{{f.pfp.url}}" alt="">
                                <a class="profileLink" href="{% url 'userProfile:Profile' f.user.username%}">  {{f.fullName}} </a>
                            </td> 
                            <td>
                                <form action="{% url 'userProfile:Profile' f.user%}" method="post" class="d-inline">
                                    {% csrf_token %}
                                    <input type="text" hidden name="next" value="{% url 'userProfile:Profile' user.username%}" />         
                                    <input type="text" hidden name="_method" id="id_method" value="delete">
                                    {% if user.id == profileInfo.user.id %}
                                        <button class="btn btnNo1" type="submit">unfriend</button>
                                    {% endif %}
                                </form>
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
          
    </div>
    {% endblock %}