Linkup_SocialNetwork/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('homePage.urls')),
    path('account/', include('accounts.urls')),
    path('u/', include('userProfile.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name= 'accounts'

urlpatterns = [
    path('login/', views.Login.as_view(), name= "login"),
    path('signup/', views.Signup.as_view(), name= "signup"),
    path('logout/', views.Logout.as_view(), name= "logout"),
    path('ajax-search/', views.UserSearch.as_view(), name= "userSearch"),
]

homePage/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from .views import HomePage

app_name= "homePage"

urlpatterns = [
    path('', login_required(HomePage.as_view()), name= "home"),
]

posts/urls.py
from posts.models import Post
from django.urls import path
from .views import *

app_name= 'Posts'

urlpatterns = [
    path('', PostView.as_view(), name= "post"),
    path('ajax-ctrls/', PostCtrlsView.as_view(), name= "postCtrls"),
]

userProfile/urls.py
from django.urls import path
from .views import *

app_name= 'userProfile'

urlpatterns = [
    path('<slug:user>', Profile.as_view(), name= "Profile"),
    path('friends/<slug:user>', FriendsCTRL.as_view(), name= "FriendsCTRL"),
]

userProfile/models.py
from django.db import models
from accounts.models import UserProfile
from django.contrib.auth.models import User

class Friend(models.Model):
    status_choices = {
        ('B', 'Binding'),
        ('F', 'Friends')
    }
    user1= models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    user2= models.ForeignKey(User, on_delete=models.CASCADE, related_name='reciver')
    status= models.CharField(choices=status_choices, max_length=2)
    
    def __str__(self):
        return (self.user1.username + " > " + self.user2.username + " = " + self.status)

    def friendList(user):
        userFriends=[]
        f1= Friend.objects.filter(user1=user.id, status= 'F').values(f_id=models.F('user2'))
        f2= Friend.objects.filter(user2=user.id, status= 'F').values(f_id=models.F('user1'))
        for f in f2:
            userFriends.append(UserProfile.objects.get(user=f['f_id']))
        for f in f1:
            userFriends.append(UserProfile.objects.get(user=f['f_id']))
        return (userFriends)

    def friendRequestsList(user):
        userFriends=[]
        allFriends= Friend.objects.filter(user2=user.id ,status= 'B').values('user1')
        for f in allFriends:
            userFriends.append(UserProfile.objects.get(user=f['user1']))
        return (userFriends)

    def sentFriendRequests(user):
        userFriends=[]
        allFriends= Friend.objects.filter(user1=user.id, status= 'B').values('user2')
        for f in allFriends:
            userFriends.append(UserProfile.objects.get(user=f['user2']))
        return (userFriends)

templates/friendList.html
{%if user.is_authenticated%}
    <div class="row">
        <div class="friendsList ms-4 position-fixed">
            <div style="border-bottom:1px solid #6c757d;">
                <h2>Friends List</h2>
            </div>
            {% for f in myFriendList %}
            <div class="row mt-4 m-auto">
                <img class="smImg col-4" src="{{f.pfp.url}}" alt="">
                <h5 class="col-8" style="place-self: center;">
                  <a class="profileLink" href="{% url 'userProfile:Profile' user=f.user.username%}">  {{f.fullName}} </a>
                </h5>
            </div>
           {% endfor %}
        </div>
    </div>
{% endif %}

templates/mainTemplate.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <title>{% block title %} {% endblock %}</title>
    </head>
    <body  data-media-url="{% get_media_prefix %}">

        {% include 'nav.html' %}
        {% include 'friendList.html' %}
        <div  style="margin: auto; margin-top: 100px; ">
            {% block content %}
            {% endblock %}
        </div>
        
        
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js" type="text/javascript"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        
        <script src="{% static 'functions.js' %}"></script>
    </body>
</html>

templates/nav.html
<nav class="navbar navbar-dark position-fixed fixed-top">
    <div  class="col-lg-4 col-md-2 col-sm-4">
        <a class="navbar-brand " href="{% url 'homePage:home' %}">Linkup</a>
    </div>
    {%if user.is_authenticated%}
        <div  class="col-lg-7 col-md-7 col-sm-7 dropdown">
            <div style="width: fit-content;" type="button" id="searchToggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <input id="userSearch" style="height: 4rem; width: 60rem;" type="text" class="search-query" placeholder="Search by username/name">
            </div>
            <div id="userSearchMenu" class="dropdown-menu" aria-labelledby="searchToggle">
                <div id="notFound" style="text-align: center; color: #fff001;">
                    <h4>Enter a valid username/Name</h4>
                </div>
            </div>
        </div>

        <div class="row col-lg-1 col-md-3 col-sm-1">

            <div class="dropdown col-3 frieRequestList">
                <span class="align-center" type="button" id="friendsRequest" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-user-plus"></i>
                </span>

                <div class="dropdown-menu dropdown-menu-right frieRequestMenu" aria-labelledby="friendsRequest">
                    <div style="border-bottom:1px solid #6c757d; text-align: center; color: #fff001;">
                        {% if not friendRequests %}
                            <h2>No Requests</h4>
                        {% else %}
                            <h2>Friend Requests</h2>
                        {% endif %}
                    </div>
                    
                    {% for f in friendRequests %}
                        <div class="frieRequestCard">
                            <div class="row m-auto">
                                <img class="smImg col-2 border-0" src="{{f.pfp.url}}" alt="">                        
                                <a class="ms-2 col-6 d-inline m-auto profileLink" href="{% url 'userProfile:Profile' user=f.user.username%}">  {{f.fullName}} </a>
                                <div class="col-4" style="align-self: center;">
                                    <form class=" d-inline" action="{% url 'userProfile:FriendsCTRL' user=f.user.username %}" method="post">
                                        {% csrf_token %}
                                        <input type="text" hidden name="_method" id="id_method" value="add">
                                        <input type="text" hidden name="status" id="id_status" value="F">  
                                        <input type="hidden" name="next" value="{{request.path}}" />         
                                        <button class="btn btnNo2">Confirm</button>
                                    </form>
                                    <form class=" d-inline" action="{% url 'userProfile:FriendsCTRL' user=f.user.username %}" method="post">
                                        {% csrf_token %}
                                        <input type="text" hidden name="_method" id="id_method" value="delete">
                                        <input type="hidden" name="next" value="{{request.path}}" />
                                        <button class="btn btnNo1">X</button>
                                    </form>    
                                </div>
                            </div>                            
                        </div>
                    {% endfor %}
                </div>
            </div>

            <img class="smImg col-4 border-0" src="{{userProfile.pfp.url}}" alt="">                        
            
            <div class="dropdown col-2">
                <span class="align-center" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <h4>
                        <i class="fa fa-sort-desc" aria-hidden="true"></i>
                    </h4>
                </span>	
                
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton" style="margin:.65rem 0 0; border-radius: 0px;">
                    <a class="dropdown-item" href="{% url 'userProfile:Profile' user=userProfile.user.username%}">Profile</a>
                    <a class="dropdown-item" href="#">Support</a>
                    <a class="dropdown-item" href="{% url 'accounts:logout' %}">Log Out</a>
                </div>
            </div>
        </div>
    {% endif %}
</nav>